  /* JOIN EXERCISES */

SELECT E.EMP_NO,E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO, D.FROM_DATE
FROM EMPLOYEES E LEFT JOIN DEPT_MANAGER D ON E.EMP_NO = D.EMP_NO 
WHERE E.LAST_NAME = 'Markovitch'
ORDER BY D.DEPT_NO DESC;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, D.DEPT_NO
FROM EMPLOYEES E JOIN DEPT_MANAGER D ON 
E.EMP_NO = D.EMP_NO
ORDER BY EMP_NO;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, S.SALARY
FROM EMPLOYEES E JOIN SALARIES S ON E.EMP_NO = S.EMP_NO
WHERE S.SALARY > 145000;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, T.TITLE
FROM EMPLOYEES E JOIN TITLES T ON E.EMP_NO = T.EMP_NO
WHERE FIRST_NAME = 'Margareta' AND LAST_NAME = 'Markovitch';

/* FOR THREE TABLES */
SELECT D.*, DM.*, E.*
FROM DEPARTMENTS D CROSS JOIN DEPT_MANAGER DM 
JOIN EMPLOYEES E ON DM.EMP_NO = E.EMP_NO
WHERE D.DEPT_NO<>DM.DEPT_NO
ORDER BY DM.EMP_NO, D.DEPT_NO;  

SELECT DM.*, D.*
FROM DEPT_MANAGER DM CROSS JOIN DEPARTMENTS D
WHERE D.DEPT_NO = 'D009'
ORDER BY D.DEPT_NO;

SELECT E.*, D.*
FROM EMPLOYEES E CROSS JOIN DEPARTMENTS D 
WHERE E.EMP_NO <10011
ORDER BY E.EMP_NO;

SELECT E.GENDER, AVG(S.SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES E JOIN SALARIES S ON 
E.EMP_NO = S.EMP_NO
ORDER BY GENDER;

SELECT E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, DM.FROM_DATE, D.DEPT_NAME
FROM EMPLOYEES E
JOIN 
DEPT_MANAGER DM ON E.EMP_NO = DM.EMP_NO
JOIN
DEPARTMENTS D ON DM.DEPT_NO = D.DEPT_NO
ORDER BY E.HIRE_DATE, D.DEPT_NAME; 


SELECT E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, T.TITLE, T.FROM_DATE, D.DEPT_NAME
FROM EMPLOYEES E JOIN TITLES T ON E.EMP_NO = T.EMP_NO
JOIN DEPT_MANAGER DM ON DM.EMP_NO = E.EMP_NO
JOIN DEPARTMENTS D ON D.DEPT_NO = DM.DEPT_NO
WHERE T.TITLE = 'MANAGER';

SELECT D.DEPT_NAME, ROUND(AVG(S.SALARY),0) AS AVG_SALARY
FROM DEPARTMENTS D JOIN DEPT_MANAGER DM ON D.DEPT_NO = DM.DEPT_NO 
JOIN SALARIES S ON S.EMP_NO = DM.EMP_NO
GROUP BY D.DEPT_NAME
HAVING AVG(S.SALARY) > 60000
ORDER BY AVG_SALARY DESC;
 
SELECT E.GENDER, COUNT(T.TITLE) AS MANAGER_COUNT
FROM EMPLOYEES E JOIN TITLES T ON E.EMP_NO = T.EMP_NO
WHERE T.TITLE = 'MANAGER'
GROUP BY GENDER
ORDER BY MANAGER_COUNT;
 
INSERT INTO EMPLOYEES_DUP
SELECT * FROM EMPLOYEES
LIMIT 20;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME,
NULL AS DEPT_NO,
NULL AS FROM_DATE
FROM EMPLOYEES_DUP E
WHERE E.EMP_NO = 10001
UNION ALL SELECT
DM.EMP_NO, DM.FROM_DATE,
NULL AS EMP_NO,
NULL AS FIRST_NAME,
NULL AS LAST_NAME
FROM DEPT_MANAGER DM;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME,
NULL AS DEPT_NO,
NULL AS FROM_DATE
FROM EMPLOYEES_DUP E
WHERE E.EMP_NO = 10001
UNION SELECT
DM.EMP_NO, DM.FROM_DATE,
NULL AS EMP_NO,
NULL AS FIRST_NAME,
NULL AS LAST_NAME
FROM DEPT_MANAGER DM;
